name: Deploy Angular build to Pages root (preserve profile/)

on:
  push:
    branches: [main]

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1) Checkout with push rights
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          persist-credentials: true

      # 2) Install Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      # 3) Install dependencies
      - name: Install dependencies
        run: npm ci

      # 4) Build Angular into a temp folder called "build"
      - name: Build Angular app
        run: npm run build -- --configuration=production --base-href=/ --output-path=build

      # 5) Remove only the old Angular artifacts (preserve profile/, .github/, etc.)
      - name: Clean previous build artifacts
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          rm -f index.html runtime.*.js polyfills.*.js main.*.js styles.*.css vendor.*.js
          rm -rf assets
          rm -f .nojekyll

      # 6) Copy the new build into the repo root
      - name: Deploy build to root
        run: |
          cp -R build/* .
          rm -rf build
          touch .nojekyll

      # 7) Commit & force‑push back to main
      - name: Commit & push to main
        run: |
          git add .
          git commit -m "ci: deploy fresh Angular build" || echo "No changes to commit"
          git push -f origin main
