name: Build & Deploy to GitHub Pages (docs/)

on:
  push:
    branches: [main]

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: true

      - uses: actions/setup-node@v3
        with:
          node-version: "18"

      - run: npm install

      - run: npm run build -- --configuration=production --base-href=/

      - name: Deploy built app to docs/
        run: |
          rm -rf docs
          mv dist/mohamedshazem docs
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add docs
          git commit -m "chore: update docs for Pages" || echo "No changes"
          git push
