name: Build & Deploy Angular to production/docs (preserve profile)

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1) Checkout main with full history
      - name: Checkout main
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          persist-credentials: true

      # 2) Setup Node.js & install dependencies
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"
      - name: Install dependencies
        run: npm ci

      # 3) Build Angular into a temporary 'build/' folder
      - name: Build Angular app
        run: npm run build -- --configuration=production --base-href=/ --output-path=build

      # 4) Checkout your production branch
      - name: Checkout production
        run: git checkout production

      # 5) Ensure docs/ exists
      - name: Ensure docs/ directory
        run: mkdir -p docs

      # 6) Clean out old docs content except profile/
      - name: Clean old docs content
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          # remove everything in docs/ except profile/
          find docs/ -mindepth 1 -maxdepth 1 \
            ! -name 'profile' \
            -exec rm -rf {} +

      # 7) Copy the fresh build into docs/
      - name: Deploy build to docs/
        run: |
          cp -R build/* docs/
          rm -rf build
          touch docs/.nojekyll

      # 8) Commit & force-push production
      - name: Commit & push to production
        run: |
          git add docs
          git commit -m "ci: deploy Angular build to docs/" || echo "No changes to commit"
          git push -f origin production
