name: Build & Deploy Angular to GitHub Pages (root)

on:
  push:
    branches: [main]

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # 1) Checkout with push permission
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          persist-credentials: true

      # 2) Install Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      # 3) Install dependencies
      - name: Install dependencies
        run: npm install

      # 4) Build the Angular app for production
      - name: Build Angular app
        run: npm run build -- --configuration=production --base-href=/

      # 5) Prepare the branch root for Pages
      - name: Clean out old files
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          # Delete everything except .github/ and .git/
          find . -maxdepth 1 -mindepth 1 ! -name '.github' ! -name '.git' -exec git rm -rf {} +

      - name: Copy build output to root
        run: |
          cp -R dist/mohamedshazem/browser/* .

      # 6) Commit & force‑push to main
      - name: Commit & push
        run: |
          git add .
          git commit -m "chore: deploy Angular build to Pages root" || echo "No changes to commit"
          git push -f origin main
