name: Build & Deploy Angular to GitHub Pages (docs/)

on:
  push:
    branches: [main]

# Allow this workflow to push back to the repo
permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1) Checkout code, with permission to push
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          persist-credentials: true

      # 2) Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      # 3) Install dependencies
      - name: Install dependencies
        run: npm install

      # 4) Build Angular app for production
      - name: Build Angular app
        run: npm run build -- --configuration=production --base-href=/

      # 5) Prepare docs/ folder
      - name: Flatten build into docs/
        run: |
          rm -rf docs
          mkdir docs
          cp -R dist/mohamedshazem/browser/* docs/

      # 6) Commit & push docs/ back to main
      - name: Commit & push docs
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add docs
          git commit -m "chore: publish build to docs/" || echo "No changes to commit"
          git push
