name: Build & Deploy to production/docs (no browser/)

on:
  push:
    branches: [main]

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout main
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          persist-credentials: true

      # 2. Setup Node & install deps
      - uses: actions/setup-node@v3
        with: { node-version: "18" }
      - run: npm ci

      # 3. Build into docs/
      - name: Build Angular into docs/
        run: npm run build -- --configuration=production --base-href=/ --output-path=docs

      # 4. Switch to production branch
      - name: Checkout production
        run: git checkout production

      # 4.1. Remove old top‑level junk
      - name: Remove old browser/ and node_modules/
        run: rm -rf browser node_modules

      # 5. Ensure docs/ exists
      - name: Ensure docs directory
        run: mkdir -p docs

      # 6. Clean old Angular files in docs/, keep profile/
      - name: Clean old docs content
        run: |
          find docs/ -mindepth 1 -maxdepth 1 \
            ! -name 'profile' \
            ! -name '.nojekyll' \
            -exec rm -rf {} +

      # 7. Commit & push
      - name: Commit & push docs/
        run: |
          git add docs
          git commit -m "ci: deploy Angular build to docs/ (no browser/)" || echo "No changes"
          git push -f origin production
