name: Build & Deploy Angular to GitHub Pages

# Run on every push to main
on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Check out code
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          persist-credentials: false # so the deploy step can push

      # 2. Install Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      # 3. Install dependencies
      - name: Install dependencies
        run: npm ci

      # 4. Build the Angular app for production
      - name: Build Angular app
        run: npm run build -- --configuration=production --base-href=/

      # 5. Deploy the build output to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist/mohamedshazem
          publish_branch: main
          allow_empty_commit: true
